defaultPolicy: block
rules:
  - sourceIP: "192.168.1.1"
    destinationIP: "*"
    port: 80
    protocol: "TCP"
    action: "allow"
  - sourceIP: "*"
    destinationIP: "192.168.1.101"
    port: 22
    protocol: "TCP"
    action: "block"
  - sourceIP: "10.0.0.1"
    destinationIP: "10.0.0.2"
    port: 0
    protocol: "*"
    action: "allow"
  - sourceIP: "*"
    destinationIP: "*"
    port: 443
    protocol: "TCP"
    action: "allow"